// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A completed report produced by a Shadow extension.
 */
export type ShadowReportItem = { id: string, shadowId: string, shadowName: string, content: string, };
